# Generated by Django 5.2.5 on 2025-12-12 04:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wiki", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_page_views", models.PositiveIntegerField(default=0)),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                ("total_article_views", models.PositiveIntegerField(default=0)),
                ("unique_articles_viewed", models.PositiveIntegerField(default=0)),
                ("avg_time_on_article", models.FloatField(blank=True, null=True)),
                ("total_searches", models.PositiveIntegerField(default=0)),
                ("searches_with_results", models.PositiveIntegerField(default=0)),
                ("searches_with_clicks", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("returning_users", models.PositiveIntegerField(default=0)),
                ("logged_in_users", models.PositiveIntegerField(default=0)),
                ("desktop_views", models.PositiveIntegerField(default=0)),
                ("mobile_views", models.PositiveIntegerField(default=0)),
                ("tablet_views", models.PositiveIntegerField(default=0)),
                ("articles_created", models.PositiveIntegerField(default=0)),
                ("articles_published", models.PositiveIntegerField(default=0)),
                ("articles_updated", models.PositiveIntegerField(default=0)),
                ("total_events", models.PositiveIntegerField(default=0)),
                ("copy_link_clicks", models.PositiveIntegerField(default=0)),
                ("edit_button_clicks", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Daily stats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=500)),
                ("full_url", models.URLField(blank=True, max_length=1000)),
                ("referrer", models.URLField(blank=True, max_length=1000, null=True)),
                ("session_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("bot", "Bot"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=50)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("time_on_page", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("time_on_article", models.PositiveIntegerField(blank=True, null=True)),
                ("scroll_depth", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="wiki.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page_view",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_view",
                        to="analytics.pageview",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=500)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("session_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("category_filter", models.CharField(blank=True, max_length=100)),
                ("type_filter", models.CharField(blank=True, max_length=50)),
                ("clicked_position", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "clicked_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_clicks",
                        to="wiki.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Search queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "period",
                    models.CharField(
                        choices=[("day", "Day"), ("week", "Week"), ("month", "Month")],
                        default="day",
                        max_length=10,
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("view_count", models.PositiveIntegerField()),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_rankings",
                        to="wiki.article",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "period", "rank"],
            },
        ),
        migrations.CreateModel(
            name="TopSearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "period",
                    models.CharField(
                        choices=[("day", "Day"), ("week", "Week"), ("month", "Month")],
                        default="day",
                        max_length=10,
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("rank", models.PositiveSmallIntegerField()),
                ("search_count", models.PositiveIntegerField()),
                ("click_through_rate", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Top search queries",
                "ordering": ["date", "period", "rank"],
                "unique_together": {("date", "period", "rank")},
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("event_action", models.CharField(max_length=100)),
                ("event_category", models.CharField(blank=True, max_length=100)),
                ("event_label", models.CharField(blank=True, max_length=255)),
                ("event_value", models.FloatField(blank=True, null=True)),
                ("page_path", models.CharField(blank=True, max_length=500)),
                ("session_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="wiki.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="analytics_e_event_t_ef40a5_idx"
                    ),
                    models.Index(
                        fields=["event_category", "created_at"],
                        name="analytics_e_event_c_f464d9_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(fields=["path", "created_at"], name="analytics_p_path_53ae0e_idx"),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["session_id", "created_at"], name="analytics_p_session_fd2f03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["user", "created_at"], name="analytics_p_user_id_51b4ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleview",
            index=models.Index(
                fields=["article", "created_at"], name="analytics_a_article_088cde_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="toparticle",
            unique_together={("date", "period", "rank")},
        ),
    ]
