# Generated by Django 5.0.7 on 2024-08-04 01:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has verified their email address.",
                verbose_name="email verified",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="verification token"
            ),
        ),
    ]
