# Generated by Django 5.0.7 on 2024-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_user_email_verified_user_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_verification_email_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last verification email sent"
            ),
        ),
    ]
