# Generated by Django 5.1.7 on 2025-06-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_customgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ebay_account_not_yet_linked_email_sent",
            field=models.BooleanField(
                default=False, verbose_name="Ebay Account Not Yet Linked Email Sent"
            ),
        ),
    ]
