# Generated by Django 5.2.5 on 2025-08-24 21:30

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0005_user_ebay_account_not_yet_linked_email_sent"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"), name="user_unique_email_ci"
            ),
        ),
    ]
