# Generated by Django 5.2.5 on 2025-12-07 14:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_user_user_unique_email_ci"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passkey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "credential_id",
                    models.BinaryField(
                        help_text="The unique identifier for this credential from the authenticator.",
                        unique=True,
                        verbose_name="credential ID",
                    ),
                ),
                (
                    "public_key",
                    models.BinaryField(
                        help_text="The public key from the authenticator.",
                        verbose_name="public key",
                    ),
                ),
                (
                    "sign_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of times this credential has been used.",
                        verbose_name="sign count",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A user-friendly name for this passkey.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The type of authenticator device.",
                        max_length=50,
                        verbose_name="device type",
                    ),
                ),
                (
                    "backed_up",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this credential is backed up.",
                        verbose_name="backed up",
                    ),
                ),
                (
                    "transports",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The list of transports supported by this credential.",
                        verbose_name="transports",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last used at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "passkey",
                "verbose_name_plural": "passkeys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasskeyChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "challenge",
                    models.BinaryField(help_text="The challenge bytes.", verbose_name="challenge"),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("authentication", "Authentication"),
                        ],
                        max_length=20,
                        verbose_name="challenge type",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email for authentication challenges when user is not yet identified.",
                        max_length=254,
                        null=True,
                        verbose_name="email",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user this challenge is for. Null for authentication challenges.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_challenges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "passkey challenge",
                "verbose_name_plural": "passkey challenges",
            },
        ),
    ]
