# Generated by Django 5.2.5 on 2025-12-07 18:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_passkeys"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the recovery code.",
                        max_length=128,
                        verbose_name="code hash",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="is used")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="used at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "recovery code",
                "verbose_name_plural": "recovery codes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TwoFactorChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "challenge_token",
                    models.CharField(max_length=64, unique=True, verbose_name="challenge token"),
                ),
                (
                    "password_verified",
                    models.BooleanField(default=True, verbose_name="password verified"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP address"),
                ),
                ("user_agent", models.TextField(blank=True, default="", verbose_name="user agent")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_challenges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "two-factor challenge",
                "verbose_name_plural": "two-factor challenges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TwoFactorMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("totp", "Authenticator App (TOTP)"),
                            ("recovery", "Recovery Codes"),
                        ],
                        max_length=20,
                        verbose_name="method type",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="Encrypted secret for TOTP methods.",
                        max_length=512,
                        verbose_name="secret",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="A user-friendly name for this 2FA method.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary 2FA method.",
                        verbose_name="is primary",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this method has been verified by the user.",
                        verbose_name="is verified",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last used at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_methods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "two-factor method",
                "verbose_name_plural": "two-factor methods",
                "ordering": ["-is_primary", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("method_type", "totp")),
                        fields=("user", "method_type"),
                        name="unique_totp_per_user",
                    )
                ],
            },
        ),
    ]
