# Generated by Django 5.2.5 on 2025-12-08 06:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_twofactor"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskeyAuthenticationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email used for authentication attempt.",
                        max_length=254,
                        null=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("auth_started", "Authentication Started"),
                            ("auth_success", "Authentication Successful"),
                            ("auth_failed", "Authentication Failed"),
                            ("auth_error", "Authentication Error"),
                            ("passkey_not_found", "Passkey Not Found"),
                            ("challenge_expired", "Challenge Expired"),
                            ("verification_failed", "Verification Failed"),
                        ],
                        max_length=50,
                        verbose_name="event type",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the authentication attempt.",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="User agent string from the request.",
                        verbose_name="user agent",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if authentication failed.",
                        verbose_name="error message",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the authentication attempt.",
                        verbose_name="metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
            ],
            options={
                "verbose_name": "passkey authentication log",
                "verbose_name_plural": "passkey authentication logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="passkeychallenge",
            index=models.Index(
                fields=["user", "challenge_type", "created_at"],
                name="authenticat_user_id_6508a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passkeychallenge",
            index=models.Index(
                fields=["email", "challenge_type", "created_at"],
                name="authenticat_email_0c4850_idx",
            ),
        ),
        migrations.AddField(
            model_name="passkeyauthenticationlog",
            name="passkey",
            field=models.ForeignKey(
                blank=True,
                help_text="The passkey used in this authentication attempt.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auth_logs",
                to="authentication.passkey",
                verbose_name="passkey",
            ),
        ),
        migrations.AddField(
            model_name="passkeyauthenticationlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user associated with this authentication attempt.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="passkey_auth_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="passkeyauthenticationlog",
            index=models.Index(
                fields=["user", "created_at"], name="authenticat_user_id_be33ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passkeyauthenticationlog",
            index=models.Index(fields=["email", "created_at"], name="authenticat_email_8c2671_idx"),
        ),
        migrations.AddIndex(
            model_name="passkeyauthenticationlog",
            index=models.Index(
                fields=["event_type", "created_at"], name="authenticat_event_t_76bb17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passkeyauthenticationlog",
            index=models.Index(
                fields=["ip_address", "created_at"], name="authenticat_ip_addr_1688e7_idx"
            ),
        ),
    ]
