# Generated by Django 5.2.5 on 2025-12-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_passkeyauthenticationlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.UUIDField(
                blank=True, editable=False, null=True, verbose_name="password reset token"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_created",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="password reset token created"
            ),
        ),
    ]
