# Generated by Django 5.2.5 on 2025-12-12 02:05

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_user_password_reset_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        help_text="Django session key for this session",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        default="unknown",
                        help_text="Type of device: desktop, mobile, tablet, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        default="Unknown Device",
                        help_text="Human-readable device name",
                        max_length=255,
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        default="Unknown", help_text="Browser name and version", max_length=100
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        default="Unknown",
                        help_text="Operating system name and version",
                        max_length=100,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", help_text="Full user agent string"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the session", null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Approximate location based on IP",
                        max_length=255,
                    ),
                ),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this session expires", null=True
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("password", "Password"),
                            ("passkey", "Passkey"),
                            ("2fa", "Two-Factor Authentication"),
                        ],
                        default="password",
                        help_text="How the user authenticated for this session",
                        max_length=50,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the user's current session (set dynamically)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_activity"], name="authenticat_user_id_d6a491_idx"
                    ),
                    models.Index(fields=["session_key"], name="authenticat_session_1fea71_idx"),
                    models.Index(fields=["expires_at"], name="authenticat_expires_8c23d2_idx"),
                ],
            },
        ),
    ]
