"""
Django settings for weddingofrebeccaandpeter project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import base64
import binascii
import logging
import os
from pathlib import Path

import django_stubs_ext
from django.templatetags.static import static

logger = logging.getLogger(__name__)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DEBUG", "0")))
DEBUG_TOOLBAR_ENABLED = bool(int(os.environ.get("DEBUG_TOOLBAR_ENABLED", "0")))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-fdg2(_6j#^s=!x*$-t#f1q6y9bu-k-4i$xrsnuv%xn@xe_r(r2"
)

if DEBUG:
    # will output to your console
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

SITE_DOMAIN = os.environ.get("SITE_DOMAIN", "localhost")

FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")

if not SITE_DOMAIN:
    raise ValueError("SITE_DOMAIN must be set.")

if DEBUG:
    ALLOWED_HOSTS: list[str] = ["*"]
else:
    ALLOWED_HOSTS = [
        "api." + SITE_DOMAIN,
    ]


WEDDING_PHOTO_UPLOAD_PASSWORD = os.environ.get("WEDDING_PHOTO_UPLOAD_PASSWORD", None)


# Application definition

INSTALLED_APPS = [
    "apps.wedding",
    "authentication",
    "corsheaders",
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inline elements are needed
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

UNFOLD = {
    "SITE_TITLE": "Wedding of Rebecca and Peter Admin",
    "SITE_HEADER": "Wedding of Rebecca and Peter Admin",
    "SITE_ICON": {
        "light": lambda request: static("logo.svg"),
        "dark": lambda request: static("logo-dark.svg"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("logo.svg"),
        "dark": lambda request: static("logo-dark.svg"),
    },
}

if DEBUG_TOOLBAR_ENABLED:
    INSTALLED_APPS += ["debug_toolbar"]

AUTH_USER_MODEL = "authentication.User"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG_TOOLBAR_ENABLED:
    MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]

AUTHENTICATION_BACKENDS = [
    "authentication.backends.EmailBackend",
]

ROOT_URLCONF = "weddingofrebeccaandpeter.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "debug": DEBUG,
        },
    },
]

ASGI_APPLICATION = "weddingofrebeccaandpeter.asgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.environ.get("SQL_DATABASE", "weddingofrebeccaandpeter_dev"),
        "USER": os.environ.get("SQL_USER", "weddingofrebeccaandpeter"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "weddingofrebeccaandpeter_dev_password"),
        "HOST": os.environ.get("SQL_HOST", "db"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
        "OPTIONS": {
            "sslmode": os.environ.get("SQL_SSL", "disable"),
        },
    }
}


# We need to check if the below settings are base64 encoded and if so, decode them. If already decoded, we can use them as is.
def decode_base64(value: str) -> str:
    try:
        decoded_value = base64.b64decode(value).decode("utf-8")
        return decoded_value
    except (binascii.Error, UnicodeDecodeError):
        return value


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

django_stubs_ext.monkeypatch()

SITE_ID = 1
SITE_NAME = "Wedding of Rebecca and Peter"

X_FRAME_OPTIONS = "SAMEORIGIN"

CSRF_COOKIE_HTTPONLY = False

CORS_ALLOWED_ORIGINS = [
    "https://" + SITE_DOMAIN,
    "https://api." + SITE_DOMAIN,
]

if DEBUG:
    CORS_ALLOWED_ORIGINS += [
        "http://localhost:3000",
    ]

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "X-CSRFToken",
    "sentry-trace",
    "baggage",
]

CORS_ALLOW_CREDENTIALS = True

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_AGE = 864000
SESSION_COOKIE_DOMAIN = "." + SITE_DOMAIN

SESSION_CACHE_ALIAS = "session"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("CACHE_BACKEND_URL", ""),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
    "session": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("SESSION_BACKEND_URL", ""),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}

if DEBUG:
    SESSION_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SECURE = True

if not DEBUG:
    CSRF_COOKIE_DOMAIN = "." + SITE_DOMAIN
