# Generated by Django 5.2.5 on 2025-12-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikiuserprofile",
            name="bluesky",
            field=models.CharField(
                blank=True, default="", help_text="Bluesky handle", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="wikiuserprofile",
            name="devto",
            field=models.CharField(
                blank=True, default="", help_text="Dev.to username", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="wikiuserprofile",
            name="facebook",
            field=models.CharField(
                blank=True, default="", help_text="Facebook profile name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="wikiuserprofile",
            name="instagram",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="wikiuserprofile",
            name="linkedin",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="wikiuserprofile",
            name="stackoverflow",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stack Overflow user ID or username",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="wikiuserprofile",
            name="twitch",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="wikiuserprofile",
            name="youtube",
            field=models.CharField(
                blank=True, default="", help_text="YouTube channel name or ID", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="wikiuserprofile",
            name="twitter",
            field=models.CharField(
                blank=True, default="", help_text="X (formerly Twitter) handle", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="wikiuserprofile",
            name="website",
            field=models.URLField(blank=True, default="", help_text="Personal website or blog"),
        ),
    ]
