# Generated by Django 5.2.5 on 2025-12-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0002_wikiuserprofile_bluesky_wikiuserprofile_devto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wikiuserprofile",
            name="bluesky",
            field=models.URLField(blank=True, default="", help_text="Bluesky profile URL"),
        ),
        migrations.AlterField(
            model_name="wikiuserprofile",
            name="devto",
            field=models.URLField(blank=True, default="", help_text="Dev.to profile URL"),
        ),
        migrations.AlterField(
            model_name="wikiuserprofile",
            name="facebook",
            field=models.URLField(blank=True, default="", help_text="Facebook profile URL"),
        ),
        migrations.AlterField(
            model_name="wikiuserprofile",
            name="github",
            field=models.URLField(blank=True, default="", help_text="GitHub profile URL"),
        ),
        migrations.AlterField(
            model_name="wikiuserprofile",
            name="instagram",
            field=models.URLField(blank=True, default="", help_text="Instagram profile URL"),
        ),
        migrations.AlterField(
            model_name="wikiuserprofile",
            name="linkedin",
            field=models.URLField(blank=True, default="", help_text="LinkedIn profile URL"),
        ),
        migrations.AlterField(
            model_name="wikiuserprofile",
            name="stackoverflow",
            field=models.URLField(blank=True, default="", help_text="Stack Overflow profile URL"),
        ),
        migrations.AlterField(
            model_name="wikiuserprofile",
            name="twitch",
            field=models.URLField(blank=True, default="", help_text="Twitch channel URL"),
        ),
        migrations.AlterField(
            model_name="wikiuserprofile",
            name="twitter",
            field=models.URLField(
                blank=True, default="", help_text="X (formerly Twitter) profile URL"
            ),
        ),
        migrations.AlterField(
            model_name="wikiuserprofile",
            name="youtube",
            field=models.URLField(blank=True, default="", help_text="YouTube channel URL"),
        ),
    ]
