# Generated by Django 5.2.5 on 2025-12-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0003_alter_wikiuserprofile_bluesky_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikiuserprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="User profile photo",
                null=True,
                upload_to="profile_photos/%Y/%m/",
            ),
        ),
    ]
