# Generated by Django 5.2.5 on 2025-12-16 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wiki", "0004_wikiuserprofile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="All categories this article belongs to",
                related_name="all_articles",
                to="wiki.category",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary category (for URL generation)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="wiki.category",
            ),
        ),
    ]
