# Generated by Django 5.2.5 on 2025-11-25 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="wedding_photos/%Y/%m/%d/")),
                (
                    "uploaded_by",
                    models.CharField(
                        help_text="Name of the guest who uploaded the photo", max_length=255
                    ),
                ),
                ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Wedding Photo",
                "verbose_name_plural": "Wedding Photos",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
