# Generated by Django 5.2.5 on 2025-11-25 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestbookMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Name of the guest", max_length=255)),
                ("message", models.TextField(help_text="Guestbook message")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Guestbook Message",
                "verbose_name_plural": "Guestbook Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
