# Generated by Django 5.2.5 on 2025-11-25 18:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wedding", "0002_guestbookmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestbookmessage",
            name="edit_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, help_text="Token for editing the message"
            ),
        ),
    ]
