# Generated by Django 5.2.5 on 2025-12-06 19:13

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wedding", "0003_guestbookmessage_edit_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("upload_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "onedrive_item_id",
                    models.CharField(
                        blank=True,
                        help_text="OneDrive/SharePoint item ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "onedrive_web_url",
                    models.URLField(
                        blank=True,
                        help_text="OneDrive/SharePoint web URL for viewing",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "onedrive_download_url",
                    models.URLField(
                        blank=True,
                        help_text="OneDrive/SharePoint download URL",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "onedrive_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="OneDrive/SharePoint embed URL for video playback",
                        max_length=2048,
                        null=True,
                    ),
                ),
                ("filename", models.CharField(help_text="Original filename", max_length=255)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("content_type", models.CharField(default="video/mp4", max_length=100)),
                (
                    "duration_seconds",
                    models.FloatField(blank=True, help_text="Video duration", null=True),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Video thumbnail image",
                        null=True,
                        upload_to="wedding_video_thumbnails/%Y/%m/%d/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "bytes_uploaded",
                    models.BigIntegerField(default=0, help_text="Bytes uploaded so far"),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("upload_session_url", models.URLField(blank=True, max_length=2048, null=True)),
                (
                    "uploaded_by",
                    models.CharField(
                        help_text="Name of the guest who uploaded the video", max_length=255
                    ),
                ),
                ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Wedding Video",
                "verbose_name_plural": "Wedding Videos",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
